### PR TITLE
Remove dependency overrides

### PR DESCRIPTION
**Pull request by kevmoo**
- drop dependency overrides for analyzer - these have shipped

### CODE REVIEW

**Comment by kevmoo** [comment]
CC @jakemac53

**Review by jakemac53 — APPROVED** [review]
I don't see the ignore for overrides?

**Comment by kevmoo** [comment]
> I don't see the ignore for overrides?

Huh?

You'll also have to land this...

**Comment by jakemac53** [comment]
> Huh?

Part the description is: `add ignore for override annotations - generator is not smart enough here (yet)`. But I don't see that?

**Comment by kevmoo** [comment]
> > Huh?
> 
> Part the description is: `add ignore for override annotations - generator is not smart enough here (yet)`. But I don't see that?

Oh! Ha. This PR did more at first. Then I shrunk it down. Remove when you merge. sorry

**Pull request merged**
